### ISSUE TITLE
Upgrade to HAPI v17

### ISSUE THREAD

**Issue by frankthelen** [ozum/hapi-locale#1]
Hi, are there any plans migrating to HAPI v17. Their plugin interface has changed. Thanks.

**Comment by ozum** [comment]
Hi,

Eventually, but first I need to learn Hapi 17 and ecosystem. Due to major changes and lack of detailed learning resources (besides API doc), this will take time.

Open to PR.

**Comment by no-more** [comment]
This is my first attempt to migrate this plugin to the new version of hapi #2

**Comment by ozum** [comment]
Thank you @no-more
