### ISSUE TITLE
Audit Vulnerabilities

### ISSUE THREAD

**Issue by rprabhakaran-aptos-com** [ozum/hapi-locale#3]
We are using latest version of hapi-locale. It has three moderate vulnerabilities that need to be fixed in hoek. Please help!

1)
Package       │ hoek 
Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3
Path          │ hapi-locale > joi > topo > hoek

2)
Package       │ hoek 
Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3
Path          │ hapi-locale > joi > hoek 

3)
Package       │ hoek 
Patched in    │ > 4.2.0 < 5.0.0 || >= 5.0.3
Path          │ api-locale > boom > hoek

**Comment by ozum** [comment]
Thanks for reporting,

All packages updated to latest versions and all tests are updated as well.

Please install latest version.

**Comment by rprabhakaran-aptos-com** [comment]
Thanks for the fix!

Is the latest version published? I am unable to see it in https://www.npmjs.com/package/hapi-locale

Please confirm once the latest version published to npm

**Comment by ozum** [comment]
@rprabhakaran-aptos-com I missed to publish. Now it is published.
